In [1]:
import os
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import cv2
VOCpath = 'subset\\ImageSets\\Main'
TrVapath = 'subset\\JPEGImages'
home = os.getcwd()
vpath = os.path.join(home, VOCpath)
tvpath = os.path.join(home, TrVapath)

In [2]:
os.chdir(vpath)
aero = dict([line.strip().split('  ') for line in open('aeroplane_trainval.txt')])
cycle = dict([line.strip().split('  ') for line in open('bicycle_trainval.txt')])
bird = dict([line.strip().split('  ') for line in open('bird_trainval.txt')])
boat = dict([line.strip().split('  ') for line in open('boat_trainval.txt')])
bottle = dict([line.strip().split('  ') for line in open('bottle_trainval.txt')])
bus = dict([line.strip().split('  ') for line in open('bus_trainval.txt')])
car = dict([line.strip().split('  ') for line in open('car_trainval.txt')])
cat = dict([line.strip().split('  ') for line in open('cat_trainval.txt')])
chair = dict([line.strip().split('  ') for line in open('chair_trainval.txt')])
cow = dict([line.strip().split('  ') for line in open('cow_trainval.txt')])
dining = dict([line.strip().split('  ') for line in open('diningtable_trainval.txt')])
dog = dict([line.strip().split('  ') for line in open('dog_trainval.txt')])
horse = dict([line.strip().split('  ') for line in open('horse_trainval.txt')])
bike = dict([line.strip().split('  ') for line in open('motorbike_trainval.txt')])
person = dict([line.strip().split('  ') for line in open('person_trainval.txt')])
sheep = dict([line.strip().split('  ') for line in open('sheep_trainval.txt')])
sofa = dict([line.strip().split('  ') for line in open('sofa_trainval.txt')])
train = dict([line.strip().split('  ') for line in open('train_trainval.txt')])
tv = dict([line.strip().split('  ') for line in open('tvmonitor_trainval.txt')])

train_val = [line.strip() for line in open('trainval.txt')]

In [50]:
os.chdir(tvpath)
feature = {}
for file in train_val:
    img = cv2.resize(cv2.imread(file+'.jpg' , cv2.IMREAD_GRAYSCALE), (256,256), interpolation = cv2.INTER_AREA)
    #img = cv2.resize(cv2.cvtColor(cv2.imread(file+'.jpg'), cv2.COLOR_BGR2GRAY), (256,256), interpolation = cv2.INTER_AREA)
    feature[file] = np.squeeze(img.ravel())
vector = np.array([(key, aero[key], cycle[key], bird[key], boat[key], bottle[key], bus[key], car[key], cat[key], chair[key], cow[key], dining[key], dog[key], horse[key], bike[key], person[key], sheep[key], sofa[key], train[key], tv[key], feature[key]) for key in train_val], dtype=object)

In [51]:
classes = ['aero', 'cycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'dining', 'dog', 'horse', 'bike', 'person', 'sheep', 'sofa', 'train', 'tv']

train_val_df = pd.DataFrame(vector, columns = ['name', 'aero', 'cycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'dining', 'dog', 'horse', 'bike', 'person', 'sheep', 'sofa', 'train', 'tv', 'feature'])

In [62]:
from sklearn import svm
from sklearn.model_selection import cross_val_score

clf = svm.SVC(kernel='linear', C=1)
classifier = svm.SVC(gamma=0.001)

classifier.fit(train_val_df['feature'].values, (train_val_df['car'].values).reshape(-1, 1))

#scores = cross_val_score(clf, train_val_df['feature'].values, train_val_df['car'].values, cv=5)

#print ("Cross Validation scores: ", scores)

#print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

ValueError: setting an array element with a sequence.

In [63]:
print(train_val_df['feature'].values)

[array([40, 39, 38, ..., 39, 43, 32], dtype=uint8)
 array([83, 89, 92, ..., 36, 39, 46], dtype=uint8)
 array([229, 232, 233, ...,  33,  33,  34], dtype=uint8)
 array([ 50,  43,  48, ..., 155, 150, 150], dtype=uint8)
 array([ 54,  56,  58, ..., 140, 140, 139], dtype=uint8)
 array([177, 171, 168, ...,  97,  98,  90], dtype=uint8)
 array([ 18,  18,  17, ..., 167, 162, 149], dtype=uint8)
 array([ 79,  77,  69, ..., 118, 123, 134], dtype=uint8)
 array([61, 55, 67, ..., 44, 42, 43], dtype=uint8)
 array([146, 145, 130, ..., 128, 147, 147], dtype=uint8)
 array([ 80,  90,  90, ..., 159, 160, 157], dtype=uint8)
 array([ 0,  0,  0, ..., 63, 63, 58], dtype=uint8)
 array([167, 165, 164, ...,   6,   6,   6], dtype=uint8)
 array([43, 43, 43, ..., 13, 18, 25], dtype=uint8)
 array([27, 27, 30, ..., 14,  5,  4], dtype=uint8)
 array([19, 25, 24, ..., 53, 23, 17], dtype=uint8)
 array([237, 227, 233, ...,  64,  64,  64], dtype=uint8)
 array([25, 32, 31, ..., 80, 92, 95], dtype=uint8)
 array([27, 25, 25, ..